services:
  db:
    image: mysql:8.0
    container_name: fluxquery-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
